name: Bug Report
description: Create a report to help us improve
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm that you have done following steps.
      options:
        - label: I have searched the existing issues for the same bug
          required: true
        - label: I have attached the log file as an attachment to this issue
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    attributes:
      label: Android Version
      description: Android Version of the phone where the App is installed
      placeholder: "14"
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: App Version where the bug happens
      placeholder: "4.0.9"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
