name: Feature request
description: Suggest an idea for this project
labels: [ "enhancement" ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm that you have done following steps.
      options:
        - label: I have searched the existing issues for the same feature
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
